# Generated by Django 4.2.7 on 2023-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente", models.CharField(max_length=100)),
                ("medico", models.CharField(max_length=100)),
                ("data", models.DateTimeField()),
            ],
        ),
    ]
