# Generated by Django 4.2.7 on 2023-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "nome_social",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
