# Generated by Django 4.2.7 on 2023-12-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0002_profissional"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consulta",
            old_name="data",
            new_name="data_consulta",
        ),
        migrations.RemoveField(
            model_name="consulta",
            name="medico",
        ),
        migrations.RemoveField(
            model_name="consulta",
            name="paciente",
        ),
        migrations.AddField(
            model_name="consulta",
            name="profissional",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultas.profissional",
            ),
            preserve_default=False,
        ),
    ]
