# Generated by Django 4.2.7 on 2023-12-02 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultas", "0003_rename_data_consulta_data_consulta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consulta",
            old_name="data_consulta",
            new_name="data",
        ),
    ]
